spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cieottest?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password:
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
   port: 8081 # This is the default port anyway, but you can change it here
cloud: 
   aws:
      region:
         auto: false
         static: ap-southeast-1
      credentials:
         accessKey: AKIAUZGMK3VHDNJY7P6B
         secretKey: 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
      stack: false
      stack.auto: false
app: 
   awsServices: 
      bucketName: mybucketttest1
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error